### ISSUE TITLE
Tareas de equipo

### ISSUE THREAD

**Issue by Emme243** [Emme243/chip#4]
### TODO: 

- [x] Asignar nuevos colores
- [x] Modificar imagen de regalo
- [x] Mejoras en el navbar: hacerlo sticky top
- [x] Mejorar la navegación: no pasar de más de 3 niveles de navegación
